name: dcewm_v2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - dash=3.0.4
  - dash-bootstrap-components=2.0.4
  - pandas=2.0.3
  - numpy=1.24.3
  - plotly=6.0.0
  - scikit-learn=1.3.0
  - pyjanitor=0.32.1
  - pandas-flavor=0.7.0
  - jupyter-dash
  - openpyxl
  - boto3
  - s3fs
  - python-dotenv
  - pyyaml
  - matplotlib
  - nbclient
  - ipykernel
  - geopandas
  - dash-ag-grid
  - geopy