name: dcewm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - dash=3.3.0
  - dash-bootstrap-components=2.0.4 
  - pandas=3.0.0
  - numpy=2.4.2
  - plotly=6.5.2
  - scikit-learn=1.6.0
  - pyjanitor=0.32.9
  - pandas-flavor=0.8.1
  - jupyter-dash
  - openpyxl
  - boto3
  - s3fs
  - python-dotenv
  - pyyaml
  - matplotlib
  - nbclient
  - ipykernel
  - geopandas
  - dash-ag-grid
  - geopy
